// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8tX_bh1iyMp68G22kN5V5voZZXGtOPaE',
    appId: '1:67686346501:web:3f2b3447d8803b32f7116c',
    messagingSenderId: '67686346501',
    projectId: 'delivrex-c8c14',
    authDomain: 'delivrex-c8c14.firebaseapp.com',
    storageBucket: 'delivrex-c8c14.appspot.com',
    measurementId: 'G-K0SKX74K0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdrbis0VNa1zh_8Mqkt2YRX73RkwyWCTY',
    appId: '1:67686346501:android:0bfbcd603f97659df7116c',
    messagingSenderId: '67686346501',
    projectId: 'delivrex-c8c14',
    storageBucket: 'delivrex-c8c14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLf0Wr0SO8bn5c0N5sxrRHatPeo-nOLc0',
    appId: '1:67686346501:ios:4968c8e5e7b8df23f7116c',
    messagingSenderId: '67686346501',
    projectId: 'delivrex-c8c14',
    storageBucket: 'delivrex-c8c14.appspot.com',
    androidClientId: '67686346501-3bst2e174l5ejoovan0utrfaa99m02t2.apps.googleusercontent.com',
    iosClientId: '67686346501-3jds59rellj10bc4mdl23t6p9nedsqvr.apps.googleusercontent.com',
    iosBundleId: 'com.delivrex.client',
  );
}
